name: The NPM package uploading

on:
  push:
    tags:
      - '*'

jobs:
  sdk-nodejs-release:
    name: 'Release NodeJS SDK'
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Generate nodejs sdk package
        run: yarn install && yarn build
      - name: set version
        run: |
          VERSION=${GITHUB_REF##*/}  # Extract the tag name
          VERSION=${VERSION#v}       # Remove the leading 'v' if present
          sed -i -e "s/\${VERSION}/${VERSION}/g" dist/package.json
      - name: Publish package to npm
        uses: JS-DevTools/npm-publish@v3
        with:
          package: dist
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
